In [1]:
#Exp no.: 2

In [2]:
#Aim:To perform operation of Data manipulation on Data set.

In [3]:
# Name : Vaishnavi Chaudhari
# Roll no : 11
# Sec : C
# Subject : DSS

In [4]:
#importing the basic library
import pandas as pd

In [5]:
import os

In [6]:
os.getcwd()

'C:\\Users\\Vaishnavi\\Downloads\\DSS'

In [7]:
os.chdir(r'C:\Users\Vaishnavi\Downloads\DSS')

In [8]:
try:
    data = pd.read_csv("diabetes.csv")
except FileNotFoundError:
    data = pd.read_csv(r"C:\Users\Vaishnavi\Downloads\DSS\diabetes.csv")

In [9]:
data.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [10]:
data.head(10)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
5,5,116,74,0,0,25.6,0.201,30,0
6,3,78,50,32,88,31.0,0.248,26,1
7,10,115,0,0,0,35.3,0.134,29,0
8,2,197,70,45,543,30.5,0.158,53,1
9,8,125,96,0,0,0.0,0.232,54,1

In [11]:
data.tail()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [12]:
#Pandas .size, .shape and .ndim are used to return size, shape and dimensions of data

In [13]:
#Returns tuple of shape (Rows, columns) of data
data.shape

(768, 9)

In [14]:
#Returns size of dataframe/series which is equivalent to total number of elements. 
#That is rows x columns.
data.size

6912

In [15]:
#Returns dimension of dataframe/series. 1 for one dimension (series), 2 for two dimension
data.ndim

2

In [16]:
data.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [17]:
data.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [18]:
# Drop is use to Drop one or more than one column from a Data 
# axis=1 i.e Column
data.drop(labels="Age",axis=1)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Outcome
0,6,148,72,35,0,33.6,0.627,1
1,1,85,66,29,0,26.6,0.351,0
2,8,183,64,0,0,23.3,0.672,1
3,1,89,66,23,94,28.1,0.167,0
4,0,137,40,35,168,43.1,2.288,1
...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,0
764,2,122,70,27,0,36.8,0.340,0
765,5,121,72,23,112,26.2,0.245,0
766,1,126,60,0,0,30.1,0.349,1
767,1,93,70,31,0,30.4,0.315,0

In [19]:
data.drop(labels=["Age","Glucose"],axis=1)

,Pregnancies,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Outcome
0,6,72,35,0,33.6,0.627,1
1,1,66,29,0,26.6,0.351,0
2,8,64,0,0,23.3,0.672,1
3,1,66,23,94,28.1,0.167,0
4,0,40,35,168,43.1,2.288,1
...,...,...,...,...,...,...,...
763,10,76,48,180,32.9,0.171,0
764,2,70,27,0,36.8,0.340,0
765,5,72,23,112,26.2,0.245,0
766,1,60,0,0,30.1,0.349,1
767,1,70,31,0,30.4,0.315,0

In [20]:
data.drop(labels=2,axis=0)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
5,5,116,74,0,0,25.6,0.201,30,0
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [21]:
data.head(10)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
5,5,116,74,0,0,25.6,0.201,30,0
6,3,78,50,32,88,31.0,0.248,26,1
7,10,115,0,0,0,35.3,0.134,29,0
8,2,197,70,45,543,30.5,0.158,53,1
9,8,125,96,0,0,0.0,0.232,54,1

In [22]:
# Drop is use to Drop one or more than one column from a Data 
# axis=0 i.e Row
data.drop(labels=[2,3],axis=0)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
4,0,137,40,35,168,43.1,2.288,33,1
5,5,116,74,0,0,25.6,0.201,30,0
6,3,78,50,32,88,31.0,0.248,26,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [23]:
# Selecting rows and columns using .iloc (first 5 rows and first 4 columns)
data.iloc[0:5, 0:4]

   Pregnancies  Glucose  BloodPressure  SkinThickness
0            6      148             72             35
1            1       85             66             29
2            8      183             64              0
3            1       89             66             23
4            0      137             40             35

In [24]:
# Filtering records based on condition (Age > 40 and Outcome == 1)
data[(data['Age'] > 40) & (data['Outcome'] == 1)].head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
8,2,197,70,45,543,30.5,0.158,53,1
9,8,125,96,0,0,0.0,0.232,54,1
13,1,189,60,23,846,30.1,0.398,59,1
14,5,166,72,19,175,25.8,0.587,51,1

In [25]:
# Sorting dataset by Glucose level in descending order
data.sort_values(by="Glucose", ascending=False).head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
661,1,199,76,43,0,42.9,1.394,22,1
561,0,198,66,32,274,41.3,0.502,28,1
228,4,197,70,39,744,36.7,2.329,31,0
8,2,197,70,45,543,30.5,0.158,53,1
579,2,197,70,99,0,34.7,0.575,62,1

In [26]:
# Grouping data by Outcome and calculating average Glucose, BMI, and Age
data.groupby('Outcome')[['Glucose', 'BMI', 'Age']].mean()

            Glucose        BMI        Age
Outcome
0        109.980000  30.304200  31.190000
1        141.257463  35.142537  37.067164

In [27]:
# Renaming column for readability
data.rename(columns={'DiabetesPedigreeFunction': 'DPF'}).head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DPF,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1