In [1]:
# Creating Series
# Student Details
# Name : Vaishnavi Chaudhari
# Roll no : 11
# Sec : C
# Subject : DSS

In [2]:
# Program for creating Series using series() method of Pandas Library

In [3]:
#Import Pandas library
import pandas as pd

In [4]:
#Creating Student Name List
Name=["Vaishnavi","Sagar","Shrikant","Lovly","Saurabh"]
Name

['Vaishnavi', 'Sagar', 'Shrikant', 'Lovly', 'Saurabh']

In [5]:
#Creating a Series 
Roll_list=pd.Series(Name,index=[1,2,3,4,5])
print(Roll_list)

1    Vaishnavi
2        Sagar
3     Shrikant
4        Lovly
5      Saurabh
dtype: object

In [6]:
# Creating Data Frame
#Import Pandas library
import pandas as pd

In [7]:
#Creating Data Frame
df=pd.DataFrame([[10,12,14,16],[11,18,15,21],[12,13,14,15]],
columns= ["CD","DBMS","DSS","CAO"])

In [8]:
df

   CD  DBMS  DSS  CAO
0  10    12   14   16
1  11    18   15   21
2  12    13   14   15

In [9]:
df.shape

(3, 4)

In [10]:
df.size

12

In [11]:
df.ndim

2

In [12]:
# Adding Record (Row) to the data frame
df2=pd.DataFrame([[5,6,7,8]],
columns= ["CD","DBMS","DSS","CAO"])

In [13]:
try:
    df3 = pd.concat([df, df2], ignore_index=True)
except Exception:
    df3 = df.append(df2, ignore_index=True)

In [14]:
df3

   CD  DBMS  DSS  CAO
0  10    12   14   16
1  11    18   15   21
2  12    13   14   15
3   5     6    7    8

In [15]:
# Adding Attribute (Columns) name DM
df3["DM"]=[12,15,16,14]

In [16]:
df3

   CD  DBMS  DSS  CAO  DM
0  10    12   14   16  12
1  11    18   15   21  15
2  12    13   14   15  16
3   5     6    7    8  14

In [17]:
# Deleting Record from  df3 dataframe
df4=df3.drop(index=[1])

In [18]:
df4

   CD  DBMS  DSS  CAO  DM
0  10    12   14   16  12
2  12    13   14   15  16
3   5     6    7    8  14

In [19]:
# Deleting Attribute (Columns) from df3 dataframe
df5=df3.drop(columns=["DM"])

In [20]:
df5

   CD  DBMS  DSS  CAO
0  10    12   14   16
1  11    18   15   21
2  12    13   14   15
3   5     6    7    8

In [21]:
#Finding mean of DSS 

print("Mean of DSS:", df5["DSS"].mean())

Mean of DSS: 12.5

In [22]:
#Finding median of DSS

print("Median of DSS:", df5["DSS"].median())

Median of DSS: 14.0

In [23]:
#Finding mode of DSS

print("Mode of DSS:", df5["DSS"].mode())

Mode of DSS: 0    14
Name: DSS, dtype: int64

In [24]:
#Finding max number of DSS

print("Max of DSS:", df5["DSS"].max())

Max of DSS: 15

In [25]:
#Finding Min number of DSS

print("Min of DSS:", df5["DSS"].min())

Min of DSS: 7